const Terms = () => (
    <div className="p-10">
        <h1 className="text-5xl">Terms and Conditions</h1>

        <div>
        <div className="WordSection1">
          <p className="MsoBodyText" style={{marginTop: '8.25pt', marginRight: '5.85pt', marginBottom: '.0001pt', marginLeft: '5.05pt', lineHeight: '102%'}}><span style={{color: '#505050'}}>Welcome to </span><a href="http://www.ghyf.org/"><span style={{color: '#505050', textDecoration: 'none'}}>www.ghyf.org </span></a><span style={{color: '#505050'}}>(the website) where you may avail facilities provided by
              Global Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation,<span style={{letterSpacing: '.05pt'}}> </span>registered<span style={{letterSpacing: '.05pt'}}> </span>under<span style={{letterSpacing: '.05pt'}}> </span></span><span style={{fontSize: '11.5pt', lineHeight: '102%', fontFamily: '"Trebuchet MS",sans-serif', color: '#272728'}}>Indian<span style={{letterSpacing: '.05pt'}}> </span>Trusts<span style={{letterSpacing: '.05pt'}}> </span>Act<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '3.45pt'}}> </span>1882<span style={{letterSpacing: '3.45pt'}}> </span></span><span style={{color: '#505050'}}>and<span style={{letterSpacing: '2.8pt'}}> </span>the<span style={{letterSpacing: '2.8pt'}}> </span>owner<span style={{letterSpacing: '2.75pt'}}> </span>of<span style={{letterSpacing: '2.8pt'}}> </span>this<span style={{letterSpacing: '.05pt'}}> </span>website.</span></p>
          <p className="MsoBodyText" style={{marginTop: '7.95pt', marginRight: '6.45pt', marginBottom: '.0001pt', marginLeft: '5.05pt', lineHeight: '105%'}}><span style={{color: '#505050'}}>From here onwards in this agreement, the term “Global
              Health Youth Foundation” refers to the<span style={{letterSpacing: '.05pt'}}> </span>website<span style={{letterSpacing: '.1pt'}}> </span></span><a href="http://www.ghyf.org/"><span style={{color: '#505050', textDecoration: 'none'}}>www.ghyf.org<span style={{letterSpacing: '.2pt'}}> </span></span></a><span style={{color: '#505050'}}>and<span style={{letterSpacing: '.1pt'}}> </span>Global<span style={{letterSpacing: '.15pt'}}> </span>Health<span style={{letterSpacing: '.2pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '.15pt'}}> </span>who<span style={{letterSpacing: '.1pt'}}> </span>owns<span style={{letterSpacing: '.05pt'}}> </span>this<span style={{letterSpacing: '.15pt'}}> </span>website.</span></p>
          <p className="MsoBodyText" style={{marginRight: '6.4pt', lineHeight: '105%'}}><span style={{color: '#505050'}}>This Terms and Conditions of Service (“Agreement”)
              between Global Health Youth Foundation<span style={{letterSpacing: '.05pt'}}> </span>and
              users / registered members of the website (“You”) describes the terms on which
              Global<span style={{letterSpacing: '.05pt'}}> </span>Health Youth Foundation offers<span style={{letterSpacing: '.05pt'}}> </span>you the Services (as defined<span style={{letterSpacing: '.05pt'}}> </span>below) through<span style={{letterSpacing: '2.75pt'}}> </span>the website. The<span style={{letterSpacing: '.05pt'}}> </span>use
              of this website is governed by the terms and conditions under this Agreement.
              Before using<span style={{letterSpacing: '.05pt'}}> </span>this website, you must
              carefully read, understand, accept and agree to abide by all the terms and<span style={{letterSpacing: '.05pt'}}> </span>conditions under this Agreement. If you do
              not agree to these terms and conditions under the<span style={{letterSpacing: '.05pt'}}> </span>Agreement,<span style={{letterSpacing: '.2pt'}}> </span>please<span style={{letterSpacing: '.25pt'}}> </span>do<span style={{letterSpacing: '.15pt'}}> </span>not<span style={{letterSpacing: '.1pt'}}> </span>use<span style={{letterSpacing: '.05pt'}}> </span>the<span style={{letterSpacing: '.15pt'}}> </span>website.</span></p>
          <p className="MsoBodyText" style={{marginRight: '6.85pt', lineHeight: '105%'}}><span style={{color: '#505050'}}>Global Health Youth Foundation reserves the right to
              revise, amend or modify the policy entailed<span style={{letterSpacing: '.05pt'}}> </span>in
              this disclaimer at any time and in any manner as it may deem fit. Any change or
              revision so<span style={{letterSpacing: '.05pt'}}> </span>effected will be posted
              on the site. It is therefore important that you review these terms regularly<span style={{letterSpacing: '.05pt'}}> </span>to<span style={{letterSpacing: '.1pt'}}> </span>ensure<span style={{letterSpacing: '.15pt'}}> </span>you<span style={{letterSpacing: '.05pt'}}> </span>are<span style={{letterSpacing: '.15pt'}}> </span>updated<span style={{letterSpacing: '.15pt'}}>
              </span>as<span style={{letterSpacing: '.1pt'}}> </span>to<span style={{letterSpacing: '.15pt'}}> </span>any<span style={{letterSpacing: '.2pt'}}> </span>changes.</span></p>
          <p className="MsoBodyText" style={{margin: '0in', marginBottom: '.0001pt', textAlign: 'left'}} align="left"><span style={{fontSize: '14.0pt'}}>&nbsp;</span></p>
          <p className="MsoBodyText" style={{marginTop: '11.8pt'}}><span style={{color: '#505050'}}>1. <span style={{letterSpacing: '.4pt'}}>&nbsp;</span>Description<span style={{letterSpacing: '-.7pt'}}> </span>of<span style={{letterSpacing: '-.6pt'}}> </span>Global<span style={{letterSpacing: '-.65pt'}}> </span>Health<span style={{letterSpacing: '-.55pt'}}>
              </span>Youth<span style={{letterSpacing: '-.75pt'}}> </span>Foundation<span style={{letterSpacing: '-.65pt'}}> </span>services</span></p>
          <p className="MsoBodyText" style={{marginTop: '8.2pt'}}><span style={{color: '#505050'}}>The<span style={{letterSpacing: '-.1pt'}}> </span>facilities<span style={{letterSpacing: '.1pt'}}> </span>and<span style={{letterSpacing: '-.1pt'}}> </span>services<span style={{letterSpacing: '-.05pt'}}> </span>provided<span style={{letterSpacing: '-.1pt'}}>
              </span>by Global<span style={{letterSpacing: '-.05pt'}}> </span>Health Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '-.1pt'}}> </span>are<span style={{letterSpacing: '-.05pt'}}> </span>as<span style={{letterSpacing: '-.05pt'}}> </span>follows,</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.2pt', marginRight: '6.5pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>1.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>1 <u>Funding
                services</u>: Global Health Youth Foundation works with various NGOs and
              display<span style={{letterSpacing: '.05pt'}}> </span>funding requirements on the
              website. Registered members can use facilities of Global Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.1pt'}}> </span>Foundation<span style={{letterSpacing: '.2pt'}}> </span>to<span style={{letterSpacing: '.15pt'}}> </span>donate<span style={{letterSpacing: '.1pt'}}> </span>to<span style={{letterSpacing: '.15pt'}}> </span>the<span style={{letterSpacing: '.1pt'}}> </span>cause<span style={{letterSpacing: '.15pt'}}> </span>they<span style={{letterSpacing: '.1pt'}}> </span>are<span style={{letterSpacing: '.15pt'}}> </span>interested<span style={{letterSpacing: '.2pt'}}> </span>in.</span></p>
          <p className="MsoListParagraph" style={{marginTop: '7.55pt', marginRight: '6.1pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>1.2<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><u><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Payment<span style={{letterSpacing: '.05pt'}}> </span>Gateway</span></u><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>: If<span style={{letterSpacing: '.05pt'}}> </span>you<span style={{letterSpacing: '.05pt'}}> </span>are<span style={{letterSpacing: '.05pt'}}> </span>making<span style={{letterSpacing: '.05pt'}}> </span>donations<span style={{letterSpacing: '.05pt'}}>
              </span>through<span style={{letterSpacing: '.05pt'}}> </span>the<span style={{letterSpacing: '.05pt'}}> </span>payment<span style={{letterSpacing: '.05pt'}}>
              </span>gateway,<span style={{letterSpacing: '.05pt'}}> </span>you<span style={{letterSpacing: '.05pt'}}> </span>understand that the payment gateway is
              provided by a third party and governed by the terms and<span style={{letterSpacing: '.05pt'}}> </span>conditions provided by such third party. You are liable in the
              event you violate any of the terms<span style={{letterSpacing: '.05pt'}}> </span>and<span style={{letterSpacing: '1.6pt'}}> </span>conditions<span style={{letterSpacing: '1.65pt'}}> </span>of<span style={{letterSpacing: '1.65pt'}}> </span>such<span style={{letterSpacing: '1.6pt'}}> </span>third<span style={{letterSpacing: '1.75pt'}}> </span>party<span style={{letterSpacing: '1.55pt'}}> </span>in<span style={{letterSpacing: '1.65pt'}}> </span>making<span style={{letterSpacing: '1.7pt'}}> </span>your<span style={{letterSpacing: '1.55pt'}}> </span>donations.<span style={{letterSpacing: '1.65pt'}}> </span>Global<span style={{letterSpacing: '1.7pt'}}>
              </span>Health<span style={{letterSpacing: '1.7pt'}}> </span>Youth<span style={{letterSpacing: '1.65pt'}}> </span>Foundation<span style={{letterSpacing: '-2.65pt'}}> </span>shall<span style={{letterSpacing: '.05pt'}}> </span>not<span style={{letterSpacing: '.1pt'}}> </span>be<span style={{letterSpacing: '.1pt'}}> </span>responsible<span style={{letterSpacing: '.1pt'}}> </span>for<span style={{letterSpacing: '.15pt'}}> </span>any<span style={{letterSpacing: '.15pt'}}> </span>such<span style={{letterSpacing: '.05pt'}}> </span>errors<span style={{letterSpacing: '.1pt'}}> </span>or<span style={{letterSpacing: '.15pt'}}> </span>default<span style={{letterSpacing: '.1pt'}}> </span>in<span style={{letterSpacing: '.1pt'}}> </span>making<span style={{letterSpacing: '.2pt'}}> </span>your<span style={{letterSpacing: '.05pt'}}> </span>donations.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.15pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>1.3<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><u><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Utilization of
                donations and Feedback reports:</span></u><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}> Global Health Youth Foundation strives to<span style={{letterSpacing: '.05pt'}}> </span>provide a feedback report on the
              utilization of donations made by you within reasonable time<span style={{letterSpacing: '.05pt'}}> </span>limits.<span style={{letterSpacing: '.05pt'}}>
              </span>The<span style={{letterSpacing: '.05pt'}}> </span>feedback<span style={{letterSpacing: '.05pt'}}> </span>report<span style={{letterSpacing: '.05pt'}}> </span>time<span style={{letterSpacing: '.05pt'}}> </span>period<span style={{letterSpacing: '.05pt'}}> </span>may<span style={{letterSpacing: '.05pt'}}> </span>vary<span style={{letterSpacing: '.05pt'}}> </span>depending<span style={{letterSpacing: '.05pt'}}> </span>on<span style={{letterSpacing: '.05pt'}}> </span>the<span style={{letterSpacing: '.05pt'}}> </span>nature<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '.05pt'}}> </span>utilization<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '-2.65pt'}}> </span>donation.</span></p>
          <p className="MsoBodyText" style={{marginRight: '6.25pt', lineHeight: '105%'}}><span style={{color: '#505050'}}>1.5 <u>Tax<span style={{letterSpacing: '.05pt'}}> </span>exemption<span style={{letterSpacing: '.05pt'}}> </span>certificates:</u> You<span style={{letterSpacing: '.05pt'}}> </span>are<span style={{letterSpacing: '.05pt'}}> </span>requested<span style={{letterSpacing: '.05pt'}}> </span>to<span style={{letterSpacing: '.05pt'}}> </span>go<span style={{letterSpacing: '.05pt'}}> </span>through<span style={{letterSpacing: '.05pt'}}>
              </span>the<span style={{letterSpacing: '.05pt'}}> </span>tax<span style={{letterSpacing: '.05pt'}}> </span>exemption<span style={{letterSpacing: '.05pt'}}> </span>details<span style={{letterSpacing: '.05pt'}}> </span>displayed in the content of every cause
              before you make the donation. Global Health Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation will<span style={{letterSpacing: '.05pt'}}> </span>ensure<span style={{letterSpacing: '.05pt'}}> </span>that<span style={{letterSpacing: '.05pt'}}> </span>applicable<span style={{letterSpacing: '.05pt'}}> </span>tax<span style={{letterSpacing: '.05pt'}}> </span>exemption<span style={{letterSpacing: '.05pt'}}> </span>certificates<span style={{letterSpacing: '.05pt'}}> </span>are<span style={{letterSpacing: '.05pt'}}> </span>send<span style={{letterSpacing: '.05pt'}}> </span>to<span style={{letterSpacing: '.05pt'}}> </span>you<span style={{letterSpacing: '.05pt'}}> </span>within<span style={{letterSpacing: '.05pt'}}> </span>reasonable<span style={{letterSpacing: '.2pt'}}> </span>time<span style={{letterSpacing: '.15pt'}}> </span>limits.</span></p>
          <p className="MsoListParagraph" style={{marginLeft: '25.5pt', textIndent: '-20.45pt'}}><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>2.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Member<span style={{letterSpacing: '.9pt'}}> </span>Information</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.25pt', marginRight: '6.4pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>2.1<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Before<span style={{letterSpacing: '.05pt'}}> </span>making<span style={{letterSpacing: '.05pt'}}> </span>any<span style={{letterSpacing: '.05pt'}}> </span>donation,<span style={{letterSpacing: '.05pt'}}>
              </span>you<span style={{letterSpacing: '.05pt'}}> </span>are<span style={{letterSpacing: '.05pt'}}> </span>required<span style={{letterSpacing: '.05pt'}}> </span>to<span style={{letterSpacing: '.05pt'}}> </span>register<span style={{letterSpacing: '.05pt'}}>
              </span>with<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation as a member by filling up all
              the mandatory information in the membership form. This<span style={{letterSpacing: '.05pt'}}> </span>information<span style={{letterSpacing: '.05pt'}}> </span>will<span style={{letterSpacing: '.05pt'}}> </span>be<span style={{letterSpacing: '.05pt'}}> </span>used<span style={{letterSpacing: '.05pt'}}> </span>for<span style={{letterSpacing: '.05pt'}}> </span>further<span style={{letterSpacing: '.05pt'}}> </span>communication<span style={{letterSpacing: '.05pt'}}> </span>in<span style={{letterSpacing: '.05pt'}}> </span>terms<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '.05pt'}}> </span>tax<span style={{letterSpacing: '.05pt'}}> </span>exemption<span style={{letterSpacing: '2.75pt'}}>
              </span>certificates,<span style={{letterSpacing: '.05pt'}}> </span>feedback reports
              etc. And also note that this is required as per Government of India order to<span style={{letterSpacing: '.05pt'}}> </span>record<span style={{letterSpacing: '.1pt'}}> </span>all<span style={{letterSpacing: '.15pt'}}> </span>the<span style={{letterSpacing: '.15pt'}}> </span>information<span style={{letterSpacing: '.2pt'}}> </span>about<span style={{letterSpacing: '.25pt'}}> </span>the<span style={{letterSpacing: '.15pt'}}> </span>donors.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.4pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>2.2<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>You acknowledge that
              all information on member profile has been entered by or on behalf of<span style={{letterSpacing: '.05pt'}}> </span>you<span style={{letterSpacing: '.05pt'}}> </span>are<span style={{letterSpacing: '.05pt'}}> </span>true<span style={{letterSpacing: '.05pt'}}> </span>to<span style={{letterSpacing: '.05pt'}}> </span>the<span style={{letterSpacing: '.05pt'}}> </span>best<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '.05pt'}}> </span>your<span style={{letterSpacing: '.05pt'}}> </span>knowledge.<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '.05pt'}}> </span>shall<span style={{letterSpacing: '2.75pt'}}> </span>take<span style={{letterSpacing: '.05pt'}}> </span>reasonable steps to maintain the
              confidentiality of such information. However, Global Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '-.1pt'}}> </span>Foundation<span style={{letterSpacing: '.05pt'}}> </span>does not<span style={{letterSpacing: '-.05pt'}}>
              </span>assume<span style={{letterSpacing: '-.1pt'}}> </span>any liability in<span style={{letterSpacing: '-.05pt'}}> </span>case<span style={{letterSpacing: '-.05pt'}}> </span>of<span style={{letterSpacing: '-.1pt'}}> </span>any<span style={{letterSpacing: '-.05pt'}}> </span>direct<span style={{letterSpacing: '-.05pt'}}> </span>or indirect<span style={{letterSpacing: '-.05pt'}}> </span>loss,<span style={{letterSpacing: '-.1pt'}}> </span>injury,<span style={{letterSpacing: '-.05pt'}}> </span>claim, </span><span style={{color: '#505050'}}>liability<span style={{letterSpacing: '.35pt'}}> </span>or<span style={{letterSpacing: '.3pt'}}> </span>damages<span style={{letterSpacing: '.35pt'}}> </span>of<span style={{letterSpacing: '.25pt'}}> </span>any<span style={{letterSpacing: '.2pt'}}> </span>kind<span style={{letterSpacing: '.25pt'}}> </span>whatsoever<span style={{letterSpacing: '.3pt'}}> </span>arising<span style={{letterSpacing: '.35pt'}}> </span>on<span style={{letterSpacing: '.25pt'}}> </span>membership<span style={{letterSpacing: '.35pt'}}> </span>of<span style={{letterSpacing: '.25pt'}}> </span>divulgence<span style={{letterSpacing: '.35pt'}}> </span>of<span style={{letterSpacing: '.25pt'}}> </span>such<span style={{letterSpacing: '-2.65pt'}}> </span>personal<span style={{letterSpacing: '.2pt'}}> </span>information<span style={{letterSpacing: '.25pt'}}> </span>by<span style={{letterSpacing: '.15pt'}}> </span>the<span style={{letterSpacing: '.1pt'}}> </span>visitor.</span></p>
        </div>
        <span style={{fontSize: '11.0pt', fontFamily: '"Microsoft Sans Serif",sans-serif'}}><br style={{pageBreakBefore: 'auto'}} clear="all" />
        </span>
        <div className="WordSection2">
          <p className="MsoListParagraph" style={{marginRight: '6.45pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>2.3<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>When
              you sign up to become a member<span style={{letterSpacing: '.05pt'}}> </span>of
              Global Health<span style={{letterSpacing: '2.75pt'}}> </span>Youth Foundation, you
              will be<span style={{letterSpacing: '.05pt'}}> </span>asked to choose a password.
              You hereby agree not to use the membership or password of<span style={{letterSpacing: '.05pt'}}> </span>another user at any time or to disclose
              your password to any third party. You agree to notify<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '.05pt'}}> </span>immediately<span style={{letterSpacing: '.05pt'}}> </span>if<span style={{letterSpacing: '.05pt'}}> </span>you<span style={{letterSpacing: '.05pt'}}> </span>suspect<span style={{letterSpacing: '.05pt'}}>
              </span>any<span style={{letterSpacing: '.05pt'}}> </span>unauthorized<span style={{letterSpacing: '.05pt'}}> </span>use<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '.05pt'}}> </span>your<span style={{letterSpacing: '.05pt'}}> </span>membership
              or access to your password. You are solely responsible for any and all use of
              your<span style={{letterSpacing: '.05pt'}}> </span>membership.</span></p>
          <p className="MsoListParagraph" style={{marginTop: '7.55pt', marginRight: '6.3pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>2.4<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>By accepting this
              Agreement, You agree that you are responsible for all information provided<span style={{letterSpacing: '.05pt'}}> </span>and subsequent activities carried by you
              on the website until you request to remove membership<span style={{letterSpacing: '.05pt'}}> </span>or we terminate your membership in accordance with the
              provisions of this agreement. Global<span style={{letterSpacing: '.05pt'}}> </span>Health
              Youth Foundation retains the right to suspend or terminate your membership
              without any<span style={{letterSpacing: '.05pt'}}> </span>further<span style={{letterSpacing: '.2pt'}}> </span>notice,<span style={{letterSpacing: '.1pt'}}> </span>due<span style={{letterSpacing: '.2pt'}}> </span>to reasons<span style={{letterSpacing: '.15pt'}}>
              </span>including<span style={{letterSpacing: '.2pt'}}> </span>but<span style={{letterSpacing: '.1pt'}}> </span>not<span style={{letterSpacing: '.1pt'}}> </span>limited<span style={{letterSpacing: '.2pt'}}> </span>to<span style={{letterSpacing: '.1pt'}}> </span>the<span style={{letterSpacing: '.1pt'}}> </span>following;</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.8pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>a)<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>breach or violate of
              these Terms or other Global Health Youth Foundation agreements or<span style={{letterSpacing: '.05pt'}}> </span>guidelines,</span></p>
          <p className="MsoListParagraph" style={{marginLeft: '17.25pt', textAlign: 'left', textIndent: '-12.25pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>b)<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>requests<span style={{letterSpacing: '-.05pt'}}> </span>by law<span style={{letterSpacing: '.05pt'}}> </span>enforcement or<span style={{letterSpacing: '.05pt'}}> </span>other<span style={{letterSpacing: '.05pt'}}> </span>government
              agencies,</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.2pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '16.65pt', textAlign: 'left', textIndent: '-11.65pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>c)<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>a request<span style={{letterSpacing: '.15pt'}}> </span>by<span style={{letterSpacing: '.1pt'}}> </span>you,</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.25pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '17.25pt', textAlign: 'left', textIndent: '-12.25pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>d)<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>unexpected technical<span style={{letterSpacing: '-.05pt'}}> </span>issues<span style={{letterSpacing: '-.05pt'}}>
              </span>or problems or,</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.2pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '17.25pt', textAlign: 'left', textIndent: '-12.25pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>e)<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>extended<span style={{letterSpacing: '-.05pt'}}> </span>periods<span style={{letterSpacing: '-.05pt'}}> </span>of<span style={{letterSpacing: '-.15pt'}}> </span>inactivity.</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.2pt', marginRight: '6.25pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>2.5<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Termination of your
              Global Health Youth Foundation membership includes removal of access<span style={{letterSpacing: '-2.65pt'}}> </span>to all offerings within the Global
              Health Youth Foundation Services and may also bar you from<span style={{letterSpacing: '.05pt'}}> </span>further use of the Global Health Youth
              Foundation Services. Furthermore, you agree that all<span style={{letterSpacing: '.05pt'}}> </span>terminations shall be made at Global Health Youth Foundation’s
              sole discretion and that Global<span style={{letterSpacing: '.05pt'}}> </span>Health
              Youth Foundation shall not be liable to neither you nor any third party for any
              termination<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '.05pt'}}> </span>your<span style={{letterSpacing: '.15pt'}}> </span>membership<span style={{letterSpacing: '.2pt'}}> </span>or<span style={{letterSpacing: '.15pt'}}> </span>access<span style={{letterSpacing: '.1pt'}}> </span>to the<span style={{letterSpacing: '.15pt'}}> </span>Global<span style={{letterSpacing: '.1pt'}}> </span>Health<span style={{letterSpacing: '.2pt'}}> </span>Youth<span style={{letterSpacing: '.2pt'}}> </span>Foundation<span style={{letterSpacing: '.1pt'}}>
              </span>Services.</span></p>
          <p className="MsoListParagraph" style={{marginTop: '7.55pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '28.4pt', textAlign: 'left', textIndent: '-20.4pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>3.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>Partner</span><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.75pt'}}> </span><span style={{fontSize: '10.5pt', color: '#505050'}}>Information</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.2pt', marginRight: '6.5pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>3.1<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Global
              Health Youth Foundation enlists Partner’s to be a part of this platform after
              screening<span style={{letterSpacing: '.05pt'}}> </span>their activities on a best
              effort basis. Global Health Youth Foundation has the sole discretion to<span style={{letterSpacing: '.05pt'}}> </span>enlist/delist<span style={{letterSpacing: '.1pt'}}> </span>Partner’s<span style={{letterSpacing: '.2pt'}}> </span>to<span style={{letterSpacing: '.1pt'}}> </span>avail<span style={{letterSpacing: '.15pt'}}> </span>its<span style={{letterSpacing: '.15pt'}}> </span>services.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.45pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>3.2<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Some
              of the content on the website is provided by various Partner’s that are enlisted.
              Such<span style={{letterSpacing: '.05pt'}}> </span>content has been reproduced
              after prior permission from the content owner i.e. Partner’s and the<span style={{letterSpacing: '.05pt'}}> </span>copyright<span style={{letterSpacing: '.05pt'}}>
              </span>of<span style={{letterSpacing: '.05pt'}}> </span>such<span style={{letterSpacing: '.05pt'}}> </span>content<span style={{letterSpacing: '.05pt'}}> </span>will<span style={{letterSpacing: '.05pt'}}> </span>remain<span style={{letterSpacing: '.05pt'}}> </span>exclusively<span style={{letterSpacing: '.05pt'}}> </span>with<span style={{letterSpacing: '.05pt'}}> </span>the<span style={{letterSpacing: '.05pt'}}> </span>Partner’s.<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation
              does not assume any responsibility for the mistakes which might appear in such<span style={{letterSpacing: '.05pt'}}> </span>content.</span></p>
          <p className="MsoListParagraph" style={{marginLeft: '28.4pt', textAlign: 'left', textIndent: '-20.4pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>4.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Donations</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.25pt', marginRight: '6.95pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>4.1<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>You
              can donate to selected causes on Global Health Youth Foundation using a number
              of<span style={{letterSpacing: '.05pt'}}> </span>payment methods such as credit or
              debit cards or cheque. Donations are processed by our<span style={{letterSpacing: '.05pt'}}> </span>payment<span style={{letterSpacing: '.2pt'}}> </span>gateway<span style={{letterSpacing: '.2pt'}}> </span>service<span style={{letterSpacing: '.15pt'}}> </span>provider<span style={{letterSpacing: '.2pt'}}> </span>Razorpay.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '5.75pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>4.2<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>All<span style={{letterSpacing: '.05pt'}}> </span>donations<span style={{letterSpacing: '.05pt'}}>
              </span>made<span style={{letterSpacing: '.05pt'}}> </span>through<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '.05pt'}}> </span>are NON-REFUNDABLE.<span style={{letterSpacing: '.05pt'}}> </span>Please contact Global Health Youth Foundation immediately if
              there are justifying reasons or<span style={{letterSpacing: '.05pt'}}> </span>circumstances
              for refund and your case may be reviewed on a best effort basis and decision of<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.2pt'}}> </span>Health<span style={{letterSpacing: '.15pt'}}> </span>Youth<span style={{letterSpacing: '.2pt'}}> </span>Foundation<span style={{letterSpacing: '.25pt'}}> </span>will<span style={{letterSpacing: '.1pt'}}> </span>be<span style={{letterSpacing: '.15pt'}}> </span>final.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.65pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>4.3<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>You will receive an
              email confirming your donation to the cause. This is the final confirmation<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '.05pt'}}> </span>your<span style={{letterSpacing: '.05pt'}}> </span>donation.<span style={{letterSpacing: '.05pt'}}>
              </span>If<span style={{letterSpacing: '.05pt'}}> </span>you have<span style={{letterSpacing: '.05pt'}}> </span>not<span style={{letterSpacing: '.05pt'}}> </span>received<span style={{letterSpacing: '.05pt'}}> </span>please<span style={{letterSpacing: '.05pt'}}> </span>contact<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '.05pt'}}> </span>immediately.</span></p>
        </div>
        <span style={{fontSize: '10.5pt', lineHeight: '105%', fontFamily: '"Microsoft Sans Serif",sans-serif'}}><br style={{pageBreakBefore: 'always'}} clear="all" />
        </span>
        <div className="WordSection3">
          <p className="MsoListParagraph" style={{marginTop: '5.2pt', marginRight: '6.65pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>4.4<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Global
              Health Youth Foundation reserves the right at any time from time to time to
              modify or<span style={{letterSpacing: '.05pt'}}> </span>discontinue,<span style={{letterSpacing: '.05pt'}}> </span>temporarily<span style={{letterSpacing: '.1pt'}}> </span>or<span style={{letterSpacing: '.1pt'}}> </span>permanently<span style={{letterSpacing: '.15pt'}}> </span>the<span style={{letterSpacing: '.05pt'}}> </span>donation<span style={{letterSpacing: '.05pt'}}> </span>facility<span style={{letterSpacing: '.15pt'}}>
              </span>with<span style={{letterSpacing: '.05pt'}}> </span>or<span style={{letterSpacing: '.1pt'}}> </span>without<span style={{letterSpacing: '.2pt'}}> </span>notice.</span></p>
          <p className="MsoListParagraph" style={{marginLeft: '25.5pt', textAlign: 'left', textIndent: '-20.45pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>5.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Prohibited<span style={{letterSpacing: '.15pt'}}> </span>Activity</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.25pt', marginRight: '6.45pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>5.1<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>You
              agree to act in a responsible and legal manner when using the Global Health
              Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '.05pt'}}> </span>Services.<span style={{letterSpacing: '.05pt'}}>
              </span>You<span style={{letterSpacing: '.05pt'}}> </span>shall<span style={{letterSpacing: '.05pt'}}> </span>comply<span style={{letterSpacing: '.05pt'}}> </span>with<span style={{letterSpacing: '.05pt'}}> </span>all<span style={{letterSpacing: '.05pt'}}> </span>applicable<span style={{letterSpacing: '.05pt'}}> </span>laws,<span style={{letterSpacing: '.05pt'}}> </span>regulations<span style={{letterSpacing: '.05pt'}}> </span>and<span style={{letterSpacing: '.05pt'}}> </span>rules<span style={{letterSpacing: '.05pt'}}> </span>and<span style={{letterSpacing: '.05pt'}}> </span>undertake
              not to use the Global Health Youth Foundation Services for any unlawful purpose
              or in<span style={{letterSpacing: '.05pt'}}> </span>a manner which is likely to
              cause harm or offense any other user including Global Health Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.95pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>5.2<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>You
              agree not to post content that is patently offensive and promotes racism,
              bigotry, hatred<span style={{letterSpacing: '.05pt'}}> </span>or<span style={{letterSpacing: '.05pt'}}> </span>harm<span style={{letterSpacing: '.25pt'}}> </span>of<span style={{letterSpacing: '.1pt'}}> </span>any<span style={{letterSpacing: '.15pt'}}> </span>kind<span style={{letterSpacing: '.1pt'}}> </span>against<span style={{letterSpacing: '.25pt'}}> </span>any<span style={{letterSpacing: '.15pt'}}> </span>group<span style={{letterSpacing: '.2pt'}}> </span>or<span style={{letterSpacing: '.2pt'}}> </span>individual;</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.7pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>5.3<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>You agree not to create
              a false identity on the website, impersonate any person or entity<span style={{letterSpacing: '.05pt'}}> </span>(including<span style={{letterSpacing: '.05pt'}}> </span>members<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation)<span style={{letterSpacing: '.05pt'}}> </span>or<span style={{letterSpacing: '.05pt'}}> </span>falsely<span style={{letterSpacing: '.05pt'}}> </span>state<span style={{letterSpacing: '.05pt'}}> </span>or<span style={{letterSpacing: '2.8pt'}}> </span>otherwise<span style={{letterSpacing: '-2.65pt'}}>
              </span>misrepresent<span style={{letterSpacing: '.15pt'}}> </span>yourself,<span style={{letterSpacing: '.05pt'}}> </span>your<span style={{letterSpacing: '.1pt'}}> </span>name,<span style={{letterSpacing: '.15pt'}}> </span>your age<span style={{letterSpacing: '.2pt'}}>
              </span>or your<span style={{letterSpacing: '.1pt'}}> </span>affiliation<span style={{letterSpacing: '.05pt'}}> </span>with<span style={{letterSpacing: '.05pt'}}> </span>any<span style={{letterSpacing: '.15pt'}}> </span>person<span style={{letterSpacing: '.05pt'}}> </span>or<span style={{letterSpacing: '.1pt'}}> </span>entity;</span></p>
          <p className="MsoListParagraph" style={{marginRight: '5.95pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>5.4<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>You
              agree not to submit or transmit through any material that contains viruses or
              any other<span style={{letterSpacing: '.05pt'}}> </span>computer codes, files or
              programs that interrupt, destroy or limit the functionality of any computer<span style={{letterSpacing: '.05pt'}}> </span>software<span style={{letterSpacing: '1.5pt'}}>
              </span>or<span style={{letterSpacing: '1.45pt'}}> </span>hardware<span style={{letterSpacing: '1.6pt'}}> </span>or<span style={{letterSpacing: '1.45pt'}}> </span>telecommunications<span style={{letterSpacing: '1.55pt'}}> </span>equipment,<span style={{letterSpacing: '1.5pt'}}> </span>or<span style={{letterSpacing: '1.55pt'}}> </span>otherwise<span style={{letterSpacing: '1.6pt'}}> </span>permit<span style={{letterSpacing: '1.6pt'}}> </span>the<span style={{letterSpacing: '1.5pt'}}> </span>unauthorized<span style={{letterSpacing: '-2.7pt'}}> </span>use of<span style={{letterSpacing: '.15pt'}}> </span>a<span style={{letterSpacing: '.15pt'}}> </span>computer<span style={{letterSpacing: '.25pt'}}>
              </span>or<span style={{letterSpacing: '.1pt'}}> </span>computer<span style={{letterSpacing: '.15pt'}}> </span>network;</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.45pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>5.5<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Global
              Health Youth Foundation reserves the right to investigate and take appropriate
              legal<span style={{letterSpacing: '.05pt'}}> </span>action against anyone who, in Global
              Health Youth Foundation’s opinion, violates this provision,<span style={{letterSpacing: '.05pt'}}> </span>including,<span style={{letterSpacing: '.1pt'}}> </span>without<span style={{letterSpacing: '.15pt'}}> </span>limitation,<span style={{letterSpacing: '.05pt'}}> </span>reporting<span style={{letterSpacing: '.15pt'}}>
              </span>you<span style={{letterSpacing: '.05pt'}}> </span>to<span style={{letterSpacing: '-.05pt'}}> </span>appropriate<span style={{letterSpacing: '.15pt'}}> </span>law<span style={{letterSpacing: '.1pt'}}> </span>enforcement<span style={{letterSpacing: '.15pt'}}> </span>authorities.</span></p>
          <p className="MsoListParagraph" style={{marginTop: '7.55pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '25.5pt', textAlign: 'left', textIndent: '-20.45pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>6.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Content</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.2pt', marginRight: '6.5pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>6.1<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>You
              are solely responsible for the content that you post on or through any of the
              Global<span style={{letterSpacing: '.05pt'}}> </span>Health Youth Foundation
              Services, and any material or information that you transmit to other<span style={{letterSpacing: '.05pt'}}> </span>users. Global Health Youth Foundation will
              not liable and does not endorse and has no control<span style={{letterSpacing: '.05pt'}}> </span>over<span style={{letterSpacing: '.05pt'}}> </span>such<span style={{letterSpacing: '.05pt'}}> </span>content.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.85pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>6.2<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>All trademarks
              reproduced in this website, which are not the property of, or licensed to
              Global<span style={{letterSpacing: '-2.65pt'}}> </span>Health<span style={{letterSpacing: '.2pt'}}> </span>Youth<span style={{letterSpacing: '.1pt'}}> </span>Foundation,<span style={{letterSpacing: '.25pt'}}> </span>are<span style={{letterSpacing: '.1pt'}}> </span>acknowledged<span style={{letterSpacing: '.25pt'}}> </span>on<span style={{letterSpacing: '.1pt'}}> </span>the<span style={{letterSpacing: '.15pt'}}> </span>website.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.3pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>6.3<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Through this website
              links to other websites are provided for your convenience to provide<span style={{letterSpacing: '.05pt'}}> </span>further information and they are not under
              the control of Global Health Youth Foundation. Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '.05pt'}}> </span>has<span style={{letterSpacing: '.05pt'}}> </span>no<span style={{letterSpacing: '.05pt'}}> </span>control<span style={{letterSpacing: '.05pt'}}>
              </span>over<span style={{letterSpacing: '.05pt'}}> </span>the<span style={{letterSpacing: '.05pt'}}> </span>nature,<span style={{letterSpacing: '.05pt'}}>
              </span>content<span style={{letterSpacing: '.05pt'}}> </span>and<span style={{letterSpacing: '.05pt'}}> </span>availability<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '.05pt'}}> </span>those<span style={{letterSpacing: '.05pt'}}> </span>websites.</span></p>
          <p className="MsoListParagraph" style={{marginTop: '7.55pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '25.5pt', textAlign: 'left', textIndent: '-20.45pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>7.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Intellectual<span style={{letterSpacing: '-.1pt'}}> </span>property<span style={{letterSpacing: '-.2pt'}}>
              </span>rights</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.2pt', marginRight: '6.55pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>7.1<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Unless<span style={{letterSpacing: '.05pt'}}> </span>otherwise<span style={{letterSpacing: '.05pt'}}>
              </span>stated,<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '.05pt'}}> </span>or<span style={{letterSpacing: '.05pt'}}> </span>our<span style={{letterSpacing: '.05pt'}}> </span>third<span style={{letterSpacing: '.05pt'}}> </span>parties<span style={{letterSpacing: '.05pt'}}> </span>own<span style={{letterSpacing: '.05pt'}}> </span>the<span style={{letterSpacing: '.05pt'}}> </span>intellectual<span style={{letterSpacing: '.1pt'}}> </span>property<span style={{letterSpacing: '.15pt'}}> </span>rights<span style={{letterSpacing: '.15pt'}}> </span>in<span style={{letterSpacing: '.1pt'}}> </span>the<span style={{letterSpacing: '.1pt'}}> </span>website<span style={{letterSpacing: '.1pt'}}> </span>and<span style={{letterSpacing: '.1pt'}}> </span>material<span style={{letterSpacing: '.15pt'}}>
              </span>on<span style={{letterSpacing: '.1pt'}}> </span>the<span style={{letterSpacing: '.1pt'}}> </span>website.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.5pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>7.2<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>You may view, download<span style={{letterSpacing: '.05pt'}}> </span>for caching<span style={{letterSpacing: '.05pt'}}> </span>purposes<span style={{letterSpacing: '.05pt'}}> </span>only, and
              print<span style={{letterSpacing: '.05pt'}}> </span>pages<span style={{letterSpacing: '.05pt'}}> </span>from the<span style={{letterSpacing: '2.75pt'}}> </span>website for<span style={{letterSpacing: '.05pt'}}> </span>your<span style={{letterSpacing: '1.15pt'}}> </span>own<span style={{letterSpacing: '1.2pt'}}> </span>personal<span style={{letterSpacing: '1.25pt'}}>
              </span>use,<span style={{letterSpacing: '1.2pt'}}> </span>subject<span style={{letterSpacing: '1.15pt'}}> </span>to<span style={{letterSpacing: '1.3pt'}}> </span>the<span style={{letterSpacing: '1.1pt'}}> </span>restrictions<span style={{letterSpacing: '1.3pt'}}> </span>set<span style={{letterSpacing: '1.1pt'}}> </span>out<span style={{letterSpacing: '1.25pt'}}> </span>below<span style={{letterSpacing: '1.35pt'}}>
              </span>and<span style={{letterSpacing: '1.25pt'}}> </span>elsewhere<span style={{letterSpacing: '1.25pt'}}> </span>in<span style={{letterSpacing: '1.3pt'}}> </span>these<span style={{letterSpacing: '1.1pt'}}> </span>terms<span style={{letterSpacing: '-2.65pt'}}>
              </span>and<span style={{letterSpacing: '.1pt'}}> </span>conditions.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.3pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>7.3<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Global Health Youth
              Foundation grants you a personal, non-transferable and non-exclusive<span style={{letterSpacing: '.05pt'}}> </span>right<span style={{letterSpacing: '.75pt'}}> </span>and<span style={{letterSpacing: '.75pt'}}> </span>license<span style={{letterSpacing: '.65pt'}}>
              </span>to<span style={{letterSpacing: '.75pt'}}> </span>use<span style={{letterSpacing: '.75pt'}}> </span>the<span style={{letterSpacing: '.65pt'}}> </span>services;<span style={{letterSpacing: '.7pt'}}> </span>provided<span style={{letterSpacing: '.75pt'}}>
              </span>that<span style={{letterSpacing: '.75pt'}}> </span>you<span style={{letterSpacing: '.7pt'}}> </span>do<span style={{letterSpacing: '.65pt'}}> </span>not<span style={{letterSpacing: '.8pt'}}> </span>(and<span style={{letterSpacing: '.75pt'}}> </span>do<span style={{letterSpacing: '.65pt'}}> </span>not<span style={{letterSpacing: '.8pt'}}> </span>allow<span style={{letterSpacing: '.8pt'}}> </span>any<span style={{letterSpacing: '.75pt'}}> </span>third<span style={{letterSpacing: '.75pt'}}> </span>party<span style={{letterSpacing: '-2.65pt'}}>
              </span>to)</span></p>
          <p className="MsoListParagraph" style={{marginLeft: '.2in', textAlign: 'left', textIndent: '-9.4pt'}} align="left"><span style={{fontSize: '9.5pt', color: '#505050', letterSpacing: '-.05pt'}}>a)<span style={{font: '7.0pt "Times New Roman"'}}> </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Sell, rent<span style={{letterSpacing: '-.05pt'}}> </span>or<span style={{letterSpacing: '-.1pt'}}> </span>sub-license<span style={{letterSpacing: '-.05pt'}}> </span>material<span style={{letterSpacing: '.05pt'}}>
              </span>from<span style={{letterSpacing: '-.05pt'}}> </span>the<span style={{letterSpacing: '-.05pt'}}> </span>website;</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.25pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '.2in', textAlign: 'left', textIndent: '-9.4pt'}} align="left"><span style={{fontSize: '9.5pt', color: '#505050', letterSpacing: '-.05pt'}}>b)<span style={{font: '7.0pt "Times New Roman"'}}> </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Show any material<span style={{letterSpacing: '-.05pt'}}> </span>from the<span style={{letterSpacing: '-.05pt'}}> </span>website<span style={{letterSpacing: '-.05pt'}}> </span>in<span style={{letterSpacing: '-.05pt'}}> </span>public,<span style={{letterSpacing: '.05pt'}}> </span>without<span style={{letterSpacing: '.05pt'}}>
              </span>accreditation<span style={{letterSpacing: '-.05pt'}}> </span>of<span style={{letterSpacing: '-.05pt'}}> </span>the<span style={{letterSpacing: '-.05pt'}}> </span>source;</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.2pt', marginRight: '6.8pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textAlign: 'left', textIndent: '0in', lineHeight: '105%'}} align="left"><span style={{fontSize: '9.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>c)<span style={{font: '7.0pt "Times New Roman"'}}>
              </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Reproduce,<span style={{letterSpacing: '1.15pt'}}> </span>duplicate,<span style={{letterSpacing: '1.2pt'}}> </span>copy<span style={{letterSpacing: '1.15pt'}}> </span>or<span style={{letterSpacing: '1.25pt'}}> </span>otherwise<span style={{letterSpacing: '1.2pt'}}> </span>exploit<span style={{letterSpacing: '1.2pt'}}> </span>material<span style={{letterSpacing: '1.3pt'}}> </span>on<span style={{letterSpacing: '1.15pt'}}> </span>Global<span style={{letterSpacing: '1.3pt'}}> </span>Health<span style={{letterSpacing: '1.2pt'}}> </span>Youth<span style={{letterSpacing: '1.3pt'}}> </span>Foundation<span style={{letterSpacing: '-2.65pt'}}> </span>website<span style={{letterSpacing: '.1pt'}}> </span>for<span style={{letterSpacing: '.2pt'}}> </span>a<span style={{letterSpacing: '.05pt'}}> </span>commercial<span style={{letterSpacing: '.15pt'}}> </span>purpose;</span></p>
        </div>
        <span style={{fontSize: '10.5pt', lineHeight: '105%', fontFamily: '"Microsoft Sans Serif",sans-serif'}}><br style={{pageBreakBefore: 'always'}} clear="all" />
        </span>
        <div className="WordSection4">
          <p className="MsoListParagraph" style={{marginTop: '5.2pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '.2in', textAlign: 'left', textIndent: '-9.4pt'}} align="left"><span style={{fontSize: '9.5pt', color: '#505050', letterSpacing: '-.05pt'}}>d)<span style={{font: '7.0pt "Times New Roman"'}}> </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Edit<span style={{letterSpacing: '-.05pt'}}>
              </span>or otherwise<span style={{letterSpacing: '.05pt'}}> </span>modify any
              material on<span style={{letterSpacing: '-.05pt'}}> </span>the<span style={{letterSpacing: '-.05pt'}}> </span>website.</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.25pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '28.4pt', textAlign: 'left', textIndent: '-20.4pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>8.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Availability</span></p>
          <p className="MsoListParagraph" style={{marginTop: '8.2pt', marginRight: '6.25pt', marginBottom: '.0001pt', marginLeft: '5.05pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>8.1<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>Global Health Youth
              Foundation aspires to be a dynamic website by adding new features and<span style={{letterSpacing: '-2.65pt'}}> </span>content regularly for the benefit of
              visitors. For this purpose Global Health Youth Foundation<span style={{letterSpacing: '.05pt'}}> </span>website<span style={{letterSpacing: '.05pt'}}>
              </span>may<span style={{letterSpacing: '.05pt'}}> </span>be<span style={{letterSpacing: '.05pt'}}> </span>temporarily<span style={{letterSpacing: '.05pt'}}> </span>shut<span style={{letterSpacing: '.05pt'}}> </span>down<span style={{letterSpacing: '.05pt'}}> </span>for<span style={{letterSpacing: '.05pt'}}> </span>updation<span style={{letterSpacing: '.05pt'}}>
              </span>work.<span style={{letterSpacing: '.05pt'}}> </span>However,<span style={{letterSpacing: '.05pt'}}> </span>Global<span style={{letterSpacing: '.05pt'}}> </span>Health<span style={{letterSpacing: '.05pt'}}> </span>Youth<span style={{letterSpacing: '.05pt'}}> </span>Foundation<span style={{letterSpacing: '.75pt'}}> </span>will<span style={{letterSpacing: '.75pt'}}> </span>put<span style={{letterSpacing: '.7pt'}}> </span>its<span style={{letterSpacing: '.65pt'}}> </span>best<span style={{letterSpacing: '.7pt'}}> </span>efforts<span style={{letterSpacing: '.75pt'}}> </span>to<span style={{letterSpacing: '.55pt'}}> </span>minimize<span style={{letterSpacing: '.8pt'}}>
              </span>the<span style={{letterSpacing: '.65pt'}}> </span>inconvenience<span style={{letterSpacing: '.8pt'}}> </span>caused<span style={{letterSpacing: '.65pt'}}> </span>due<span style={{letterSpacing: '.7pt'}}> </span>to<span style={{letterSpacing: '.65pt'}}> </span>non-availability<span style={{letterSpacing: '-2.7pt'}}> </span>of<span style={{letterSpacing: '.1pt'}}> </span>website.</span></p>
          <p className="MsoListParagraph" style={{marginRight: '6.8pt', textIndent: '0in', lineHeight: '105%'}}><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050', letterSpacing: '-.05pt'}}>8.2<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', lineHeight: '105%', color: '#505050'}}>At Global Health Youth
              Foundation we make every effort is made to keep the website up and<span style={{letterSpacing: '.05pt'}}> </span>running smoothly. However, Global Health
              Youth Foundation takes no responsibility for, and will<span style={{letterSpacing: '.05pt'}}> </span>not be liable for, the website<span style={{letterSpacing: '.1pt'}}>
              </span>being<span style={{letterSpacing: '.1pt'}}> </span>temporarily<span style={{letterSpacing: '.15pt'}}> </span>unavailable<span style={{letterSpacing: '.1pt'}}> </span>due<span style={{letterSpacing: '.1pt'}}> </span>to<span style={{letterSpacing: '-.1pt'}}> </span>issues beyond<span style={{letterSpacing: '.1pt'}}> </span>our<span style={{letterSpacing: '.05pt'}}> </span>control.</span></p>
          <p className="MsoListParagraph" style={{marginLeft: '28.4pt', textAlign: 'left', textIndent: '-20.4pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>9.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Indemnification</span></p>
          <p className="MsoBodyText" style={{marginTop: '8.25pt', marginRight: '6.4pt', marginBottom: '.0001pt', marginLeft: '5.05pt', lineHeight: '105%'}}><span style={{color: '#505050'}}>9.1<span style={{letterSpacing: '2.2pt'}}> </span>By<span style={{letterSpacing: '2.3pt'}}> </span>accepting<span style={{letterSpacing: '2.25pt'}}>
              </span>these<span style={{letterSpacing: '2.25pt'}}> </span>Terms,<span style={{letterSpacing: '2.2pt'}}> </span>you<span style={{letterSpacing: '2.25pt'}}> </span>agree<span style={{letterSpacing: '2.35pt'}}> </span>to<span style={{letterSpacing: '2.15pt'}}> </span>indemnify<span style={{letterSpacing: '2.25pt'}}> </span>and<span style={{letterSpacing: '2.35pt'}}> </span>otherwise<span style={{letterSpacing: '2.25pt'}}> </span>hold<span style={{letterSpacing: '2.3pt'}}> </span>harmless<span style={{letterSpacing: '2.25pt'}}> </span>Global<span style={{letterSpacing: '-2.65pt'}}>
              </span>Health Youth Foundation, its officers, employees, affiliates and other
              partners from any direct,<span style={{letterSpacing: '.05pt'}}> </span>indirect,
              incidental, special, consequential or exemplary damages resulting from the use
              of the<span style={{letterSpacing: '.05pt'}}> </span>Global Health Youth Foundation
              Services by you or by those who have access to the service<span style={{letterSpacing: '.05pt'}}> </span>through<span style={{letterSpacing: '.1pt'}}> </span>your<span style={{letterSpacing: '.2pt'}}> </span>membership.</span></p>
          <p className="MsoListParagraph" style={{marginLeft: '25.5pt', textAlign: 'left', textIndent: '-17.5pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>10.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>Privacy</span><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.65pt'}}> </span><span style={{fontSize: '10.5pt', color: '#505050'}}>and<span style={{letterSpacing: '-.7pt'}}> </span>Disclosure</span></p>
          <p className="MsoBodyText" style={{marginTop: '8.2pt', marginRight: '5.8pt', marginBottom: '.0001pt', marginLeft: '5.05pt', lineHeight: '105%'}}><span style={{color: '#505050'}}>10.1 Use of the Global Health Youth Foundation services
              is also governed by our Privacy Policy,<span style={{letterSpacing: '.05pt'}}> </span>which
              is incorporated into these terms by this reference. Without limitation of the
              terms and<span style={{letterSpacing: '.05pt'}}> </span>conditions set forth in our
              you understand and agree that Global Health Youth Foundation may<span style={{letterSpacing: '.05pt'}}> </span>disclose personally identifiable
              information if required to do so by law or in the good faith belief<span style={{letterSpacing: '.05pt'}}> </span>that such disclosure is necessary to
              comply<span style={{letterSpacing: '2.75pt'}}> </span>with legal<span style={{letterSpacing: '2.8pt'}}> </span>process, enforce these terms or protect<span style={{letterSpacing: '.05pt'}}> </span>the rights, property<span style={{letterSpacing: '.2pt'}}> </span>or<span style={{letterSpacing: '-.05pt'}}> </span>safety<span style={{letterSpacing: '.05pt'}}> </span>of<span style={{letterSpacing: '-.05pt'}}> </span>Global<span style={{letterSpacing: '.1pt'}}> </span>Health<span style={{letterSpacing: '.15pt'}}> </span>Youth
              Foundation, its<span style={{letterSpacing: '.05pt'}}> </span>members<span style={{letterSpacing: '.05pt'}}> </span>and<span style={{letterSpacing: '.15pt'}}> </span>the
              public.</span></p>
          <p className="MsoListParagraph" style={{marginTop: '7.55pt', marginRight: '0in', marginBottom: '.0001pt', marginLeft: '25.5pt', textAlign: 'left', textIndent: '-17.5pt'}} align="left"><span style={{fontSize: '10.5pt', color: '#505050', letterSpacing: '-.05pt'}}>11.<span style={{font: '7.0pt "Times New Roman"'}}>&nbsp; </span></span><span style={{fontSize: '10.5pt', color: '#505050'}}>Governing<span style={{letterSpacing: '1.15pt'}}> </span>Law/Dispute<span style={{letterSpacing: '1.3pt'}}> </span>Resolution</span></p>
          <p className="MsoBodyText" style={{marginTop: '8.2pt', marginRight: '6.55pt', marginBottom: '.0001pt', marginLeft: '5.05pt', lineHeight: '105%'}}><span style={{color: '#505050'}}>11.1 The contract shall be governed in accordance with
              the laws of India and the Courts in<span style={{letterSpacing: '.05pt'}}> </span>Hyderabad<span style={{letterSpacing: '.05pt'}}> </span>shall<span style={{letterSpacing: '.05pt'}}> </span>have<span style={{letterSpacing: '.05pt'}}> </span>the<span style={{letterSpacing: '.05pt'}}> </span>exclusive<span style={{letterSpacing: '.05pt'}}> </span>jurisdiction<span style={{letterSpacing: '.05pt'}}> </span>to<span style={{letterSpacing: '.05pt'}}> </span>try<span style={{letterSpacing: '.05pt'}}> </span>and<span style={{letterSpacing: '.05pt'}}> </span>suit,<span style={{letterSpacing: '.05pt'}}> </span>proceedings<span style={{letterSpacing: '.05pt'}}> </span>in<span style={{letterSpacing: '.05pt'}}> </span>connection<span style={{letterSpacing: '.05pt'}}> </span>therewith/in<span style={{letterSpacing: '.05pt'}}> </span>that<span style={{letterSpacing: '.05pt'}}> </span>behalf.<span style={{letterSpacing: '.05pt'}}> </span>Any<span style={{letterSpacing: '.05pt'}}> </span>disputes<span style={{letterSpacing: '.05pt'}}> </span>under<span style={{letterSpacing: '.05pt'}}> </span>this<span style={{letterSpacing: '.05pt'}}> </span>agreement,<span style={{letterSpacing: '.05pt'}}> </span>which<span style={{letterSpacing: '.05pt'}}> </span>cannot<span style={{letterSpacing: '.05pt'}}> </span>be<span style={{letterSpacing: '.05pt'}}> </span>settled<span style={{letterSpacing: '.05pt'}}> </span>by<span style={{letterSpacing: '.05pt'}}> </span>negotiation<span style={{letterSpacing: '.05pt'}}> </span>may<span style={{letterSpacing: '.05pt'}}> </span>be<span style={{letterSpacing: '.05pt'}}> </span>resolved<span style={{letterSpacing: '.05pt'}}>
              </span>exclusively<span style={{letterSpacing: '.05pt'}}> </span>by<span style={{letterSpacing: '.05pt'}}> </span>arbitration<span style={{letterSpacing: '.05pt'}}> </span>and<span style={{letterSpacing: '.05pt'}}> </span>shall<span style={{letterSpacing: '.05pt'}}> </span>be<span style={{letterSpacing: '.05pt'}}> </span>held<span style={{letterSpacing: '.05pt'}}> </span>in<span style={{letterSpacing: '2.75pt'}}> </span>Hyderabad,<span style={{letterSpacing: '.05pt'}}> </span>Telangana<span style={{letterSpacing: '.05pt'}}>
              </span>State<span style={{letterSpacing: '.05pt'}}> </span>, India<span style={{letterSpacing: '.05pt'}}> </span>and<span style={{letterSpacing: '.05pt'}}> </span>conducted<span style={{letterSpacing: '.05pt'}}> </span>in<span style={{letterSpacing: '.05pt'}}> </span>accordance<span style={{letterSpacing: '.05pt'}}> </span>with<span style={{letterSpacing: '.05pt'}}> </span>the<span style={{letterSpacing: '.05pt'}}> </span>provision<span style={{letterSpacing: '.05pt'}}>
              </span>of<span style={{letterSpacing: '.05pt'}}> </span>Arbitration<span style={{letterSpacing: '.05pt'}}> </span>and<span style={{letterSpacing: '.05pt'}}> </span>Conciliation
              Act, 1996 or any statutory modification or re-enactment thereof.\ Subject to
              the<span style={{letterSpacing: '.05pt'}}> </span>above, the courts of law at
              Hyderabad alone shall have the jurisdiction in respect of all matters<span style={{letterSpacing: '.05pt'}}> </span>connected<span style={{letterSpacing: '.15pt'}}>
              </span>with<span style={{letterSpacing: '.1pt'}}> </span>the<span style={{letterSpacing: '.1pt'}}> </span>agreement.<span style={{letterSpacing: '.1pt'}}> </span>The<span style={{letterSpacing: '.1pt'}}> </span>arbitration<span style={{letterSpacing: '.15pt'}}> </span>award<span style={{letterSpacing: '.1pt'}}> </span>shall<span style={{letterSpacing: '.1pt'}}> </span>be<span style={{letterSpacing: '.1pt'}}> </span>final<span style={{letterSpacing: '.1pt'}}> </span>and<span style={{letterSpacing: '.05pt'}}> </span>binding.</span></p>
        </div>
      </div>

    </div>
);

export default Terms;